name: "Upstream Sync"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: cheat-engine/cheat-engine
        env:
          UNSHALLOW: true
      - name: Start build
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: buildCE.yml
      - name: Download artifact
        if: steps.sync.outputs.has_new_commits == 'false'
        uses: ardittristan/actions-download-artifact@master
        with:
          name: Release
          latest: true
          path: artifact
      - name: Upload artifact
        if: steps.sync.outputs.has_new_commits == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: artifact
