name: Purge Cache

on:
  workflow_dispatch:
    inputs:
      max-age:
        default: "0"

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@master
        with:
          max-age: ${{ inputs.max-age }}
          accessed: false
          created: true
